# ══════════════════════════════════════════════════════
#  Redis Sentinel — Clinique Connectée
#  3 sentinelles surveillent le master clinique_master
# ══════════════════════════════════════════════════════

# Adresse d'écoute
port 26379
dir "/tmp"
bind 0.0.0.0

# Résolution DNS des noms d'hôte Docker (obligatoire pour utiliser
# des noms de service Compose comme "redis_master" au lieu d'IP figées).
# DOIT être placé AVANT la ligne "sentinel monitor" (parsing séquentiel).
sentinel resolve-hostnames yes
sentinel announce-hostnames yes

# Surveillance du master Redis
sentinel monitor clinique_master redis_master 6379 2

# Authentification vers le master/replicas
sentinel auth-pass clinique_master tp-iot26@

# Délai avant de considérer le master comme mort (ms)
sentinel down-after-milliseconds clinique_master 5000

# Timeout du failover (ms)
sentinel failover-timeout clinique_master 10000

# Nombre de replicas à reconfigurer en parallèle pendant failover

# Logs
loglevel notice
# Generated by CONFIG REWRITE
latency-tracking-info-percentiles 50 99 99.9
user default on nopass sanitize-payload ~* &* +@all
sentinel myid c98a86bb34b3aab518bd31eb41adf8d1f1eb5fec
sentinel config-epoch clinique_master 3
sentinel leader-epoch clinique_master 3
sentinel current-epoch 3

sentinel known-replica clinique_master 172.20.0.17 6379

sentinel known-replica clinique_master 172.20.0.4 6379

sentinel known-sentinel clinique_master 172.20.0.20 26379 c98a86bb34b3aab518bd31eb41adf8d1f1eb5fec

sentinel known-sentinel clinique_master 172.20.0.21 26379 127948cda3b4c80942dbda482470250750f676bd

sentinel known-replica clinique_master 172.20.0.3 6379

sentinel known-replica clinique_master 172.20.0.9 6379

sentinel known-sentinel clinique_master 172.20.0.22 26379 bb27d3fa2c1c582ec3f86ccc3f18a1a179bc86ec

sentinel known-replica clinique_master 172.20.0.10 6379

sentinel known-replica clinique_master 172.20.0.13 6379
