# ══════════════════════════════════════════════════════════════
#  CLINIQUE CONNECTÉE — telegraf.conf
#  Pipeline : MQTT Mosquitto → Telegraf → InfluxDB 2.7
# ══════════════════════════════════════════════════════════════

[agent]
  interval            = "10s"
  round_interval      = true
  flush_interval      = "10s"
  flush_jitter        = "2s"
  metric_batch_size   = 1000
  metric_buffer_limit = 10000
  hostname            = "telegraf-clinique"
  omit_hostname       = false

# ══════════════════════════════════════════════════════════════
#  INPUT — MQTT Consumer
# ══════════════════════════════════════════════════════════════

[[inputs.mqtt_consumer]]
  servers   = ["ssl://clinique_mosquitto:8883"]
  client_id = "telegraf-clinique-001"
  qos       = 0
  insecure_skip_verify = true
  username  = "telegraf_agent"
  password  = "clinique2026"

  topics = [
    "clinique/chambre/+/vitaux",
    "clinique/chambre/+/co2",
    "clinique/chambre/+/mouvement",
    "clinique/chambre/+/perfuseur",
    "clinique/chambre/+/appel",
    "clinique/chambre/+/appel_securite",
    "clinique/acces/+/porte",
    "clinique/acces/+/badge",
    "clinique/securite/+/camera",
    "clinique/energie/ups",
    "clinique/energie/generateur",
    "clinique/energie/compteur/+",
    "clinique/alerte/controleur"
  ]

  data_format        = "influx"
  connection_timeout = "30s"

# ══════════════════════════════════════════════════════════════
#  OUTPUT — InfluxDB v2 (bucket principal)
# ══════════════════════════════════════════════════════════════

[[outputs.influxdb_v2]]
  urls         = ["http://clinique_influxdb:8086"]
  token        = "mon-super-token-123456789"
  organization = "clinique_abidjan"
  bucket       = "mesures_capteurs"
  timeout      = "30s"

# ══════════════════════════════════════════════════════════════
#  OUTPUT — InfluxDB v2 (bucket sécurité — filtré)
# ══════════════════════════════════════════════════════════════

[[outputs.influxdb_v2]]
  urls         = ["http://clinique_influxdb:8086"]
  token        = "mon-super-token-123456789"
  organization = "clinique_abidjan"
  bucket       = "logs_securite"
  timeout      = "30s"

  [outputs.influxdb_v2.tagpass]
    _measurement = ["appel_securite", "securite_acces", "badge_acces", "camera_intrusion"]


[[processors.converter]]
  namepass = ["vitaux_chambre"]
  [processors.converter.fields]
    float = ["spo2", "ecg_bpm", "temperature", "pression_sys", "pression_dia"]
# ══════════════════════════════════════════════════════════════
#  MONITORING TELEGRAF INTERNE
# ══════════════════════════════════════════════════════════════

[[inputs.internal]]
  collect_memstats = true